### ISSUE TITLE
Wrong text colours in lists

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/einsteinium#1]
The launcher seems to use B_CONTROL_TEXT_COLOR as text colour in the list. It should use B_LIST_ITEM_TEXT_COLOR and when selected B_LIST_SELECTED_ITEM_TEXT_COLOR.
One onnly sees those things when using custom colours in Appearance. I, for example, use white on blue for selected menus and lists.

**Comment by Perelandra0x309** [comment]
Changed to use ui_color with Haiku color definitions in v1.3.1
