### ISSUE TITLE
The bootscript could clean up after itself

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/einsteinium#2]
Since Einsteinium is pretty much guaranteed to be used with package management, and since the EinsteiniumBootscript will be installed again automatically if the package was uninstalled and then re-installed, the notification when it can't find the Einsteinium daemon and engine isn't really useful, is it?
I have uninstalled Einsteinium and am now greeted with two notifications on bootup. :)

Wouldn't it be more useful, it the EinsteiniumBootscript would delete itself if Einsteinium was uninstalled, i.e. the daemon and engine weren't found? Would be kinda neat, IMO.

**Comment by Perelandra0x309** [comment]
@humdingerb Thank you for these suggestions.  I am working on a minor update so will take these into consideration.
Is there a way to query if a package is installed, maybe other than just checking the two packages directories?

**Comment by humdingerb** [comment]
You could query for our app's signature on the boot volume, which should work for your average enduser. Things my get difficult if a user figures out how to mount package locations outside of /boot (I don't know if/how that's possible), or if someone grabs the source and builds from there...
To save looking in two locations, there's also /system/package-links which AFAIK is virtual folder gathering all mounted package loacations.

**Comment by Perelandra0x309** [comment]
Added logic to bootscript to delete itsself if package not installed.
